import { Inter, Karla } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // load weights you’ll use
  variable: "--font-inter",
});

const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // load weights you’ll use
  variable: "--font-oswald",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${karla.variable} antialiased `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
